version: '3.8'

services:
  tibia-agent:
    build:
      dockerfile: agent/Dockerfile
    container_name: tibia-agent
    ports:
      - "8045:8000"
    env_file:
      - ./agent/.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - ticket-app_ticket-app_postgres_network 

networks:
  ticket-app_ticket-app_postgres_network :
    external: true  # Use the existing network
  